version: '2'
services:
    svn2git-app:
        image: svn2git
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://svn2git-mysql:3306/svn2git?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    svn2git-mysql:
        extends:
            file: mysql.yml
            service: svn2git-mysql
